// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeM7_S3omWWbpf04mVMYZ8Ohy4iPVlCAI',
    appId: '1:34420490444:web:4826d94678326d6fbd8269',
    messagingSenderId: '34420490444',
    projectId: 'itiflutterproject',
    authDomain: 'itiflutterproject.firebaseapp.com',
    storageBucket: 'itiflutterproject.firebasestorage.app',
    measurementId: 'G-VD7BQ3DF1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYijw6wHaGfJDHNuOtoWyaAORZS4TTDyA',
    appId: '1:34420490444:android:80d548f276276e47bd8269',
    messagingSenderId: '34420490444',
    projectId: 'itiflutterproject',
    storageBucket: 'itiflutterproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-qTKFIX36gz4-VMqeQ9shX7MwyG9ss34',
    appId: '1:34420490444:ios:bc22f2fb6f265293bd8269',
    messagingSenderId: '34420490444',
    projectId: 'itiflutterproject',
    storageBucket: 'itiflutterproject.firebasestorage.app',
    iosClientId: '34420490444-8ht0glf2ndujkphdic5u7952657vk8le.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-qTKFIX36gz4-VMqeQ9shX7MwyG9ss34',
    appId: '1:34420490444:ios:bc22f2fb6f265293bd8269',
    messagingSenderId: '34420490444',
    projectId: 'itiflutterproject',
    storageBucket: 'itiflutterproject.firebasestorage.app',
    iosClientId: '34420490444-8ht0glf2ndujkphdic5u7952657vk8le.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeM7_S3omWWbpf04mVMYZ8Ohy4iPVlCAI',
    appId: '1:34420490444:web:074268a42f23fd90bd8269',
    messagingSenderId: '34420490444',
    projectId: 'itiflutterproject',
    authDomain: 'itiflutterproject.firebaseapp.com',
    storageBucket: 'itiflutterproject.firebasestorage.app',
    measurementId: 'G-07468PNXFZ',
  );
}
